## Global Variabel
@BaseUrl = https://pam-2026-p5-ifs23019-be.annyklaudya.site:8080
# @BaseUrl = http://127.0.0.1:8000

### ---------------------------------------
## Auth
### ---------------------------------------

### Melakukan pendaftaran
# @name PostRegister
POST {{BaseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Anny Klaudya",
  "username": "annyklaudya",
  "password": "password123"
}

### Masuk ke layanan
# @name PostLogin
POST {{BaseUrl}}/auth/login
Content-Type: application/json

{
  "username": "annyklaudya",
  "password": "password123"
}

> {%
    client.global.set("authToken", response.body.data.authToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### Keluar dari layanan
# @name PostLogout
POST {{BaseUrl}}/auth/logout
Content-Type: application/json

{
  "authToken": "{{authToken}}"
}

### Refresh Token
# @name PostRefreshToken
POST {{BaseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "authToken": "{{authToken}}",
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("authToken", response.body.data.authToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### ---------------------------------------
## Users
### ---------------------------------------

### Mengambil informasi akun
# @name GetUserMe
GET {{BaseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

> {%
    client.global.set("userId", response.body.data.user.id);
%}

### Mengubah informasi akun
# @name PutUserMe
PUT {{BaseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Anny Klaudya Hutabarat",
  "username": "annyklaudya",
  "about": "Informatics Student at IT Del | SM Ent Enthusiast"
}

### ---------------------------------------
## Artists (SM Entertainment)
### ---------------------------------------

### Mengambil daftar Artis dengan Pagination dan Filter
# Parameter: page, perPage, is_active (true/false), group_name (NCT/aespa/Red Velvet)
# @name GetArtists
GET {{BaseUrl}}/artists?page=1&perPage=10&is_active=true&group_name=aespa&search=
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Menambahkan data Artis baru
# @name PostArtist
POST {{BaseUrl}}/artists
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Karina",
  "groupName": "aespa",
  "position": "Leader, Main Dancer",
  "isActive": true
}

> {%
    // Menyimpan artistId untuk pengujian berikutnya
    client.global.set("artistId", response.body.data.artistId);
%}

### Mengambil data artis berdasarkan ID
# @name GetArtistById
GET {{BaseUrl}}/artists/{{artistId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Mengubah data artis (Teks)
# @name PutArtist
PUT {{BaseUrl}}/artists/{{artistId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Karina",
  "groupName": "aespa",
  "position": "Leader, Face of the Group",
  "isActive": true
}

### Mengubah foto profil artis
# @name PutArtistPhoto
PUT {{BaseUrl}}/artists/{{artistId}}/photo
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="karina.png"
Content-Type: image/png

< ./uploads/examples/karina.png
--WebAppBoundary--

### Mengambil statistik Artis (Total, Aktif, Tidak Aktif)
# @name GetArtistStats
GET {{BaseUrl}}/artists/stats
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Mengambil foto artis
# @name GetArtistPhoto
GET {{BaseUrl}}/images/artists/{{artistId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### Menghapus data artis
# @name DeleteArtist
DELETE {{BaseUrl}}/artists/{{artistId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json